"""Offline self-test (no network, no LLM): python test_auto_run.py  or  start.bat test"""
import sys, tempfile, unittest
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
import auto_run as a


class T(unittest.TestCase):
    def setUp(self):
        self.d = Path(tempfile.mkdtemp())
        self.log = a.Log(self.d / "l.jsonl")
        self.sh = a.Shell(self.d, self.log)

    def test_url_validation(self):
        for bad in ("http://github.com/a/b", "https://evil.com/a/b", "https://github.com/a/b; rm -rf /"):
            with self.assertRaises(SystemExit):
                a.clone(bad, self.d, self.log)

    def test_shell_ok_and_fail(self):
        self.assertEqual(self.sh.run("python -c \"print(1)\"").code, 0)
        self.assertNotEqual(self.sh.run("python -c \"raise SystemExit(3)\"").code, 0)

    def test_guess_run(self):
        (self.d / "main.py").write_text("print(1)")
        self.assertEqual(a.guess_run(self.d), "python main.py")

    def test_candidate_files_from_traceback(self):
        (self.d / "bad.py").write_text("raise ValueError('x')")
        r = self.sh.run("python bad.py")
        self.assertEqual([p.name for p in a.candidate_files(self.d, r.err)], ["bad.py"])

    def test_run_with_fixes_no_ai_fails_cleanly(self):
        (self.d / "main.py").write_text("raise SystemExit(1)")
        self.assertFalse(a.run_with_fixes(self.d, self.sh, "python main.py", 3, None, self.log))

    def test_ai_patch_path_traversal_rejected(self):
        (self.d / "main.py").write_text("print(x)")
        orig = a.llm
        a.llm = lambda p, prov: '{"file": "../evil.py", "content": "boom", "why": "t"}'
        try:
            res = a.Result(1, "", 'File "%s", line 1' % (self.d / "main.py"))
            self.assertFalse(a.ai_fix(self.d, "python main.py", res, self.log, "ollama"))
        finally:
            a.llm = orig

    def test_write_launcher(self):
        (self.d / ".venv" / "Scripts").mkdir(parents=True)
        (self.d / ".venv" / "Scripts" / "activate.bat").write_text("")
        p = a.write_launcher(self.d, "python main.py --x 100%", self.log)
        txt = p.read_text()
        self.assertEqual(p.name, "start.bat")
        self.assertIn("call python main.py --x 100%%", txt)
        self.assertIn("activate.bat", txt)
        self.assertIn(b"\r\n", p.read_bytes())

    def test_launcher_does_not_overwrite_repo_bat(self):
        (self.d / "start.bat").write_text("@echo mine")
        p = a.write_launcher(self.d, "npm start", self.log)
        self.assertEqual(p.name, "start.autorun.bat")
        self.assertEqual((self.d / "start.bat").read_text(), "@echo mine")
        # our own generated file is safe to refresh
        (self.d / "start.bat").write_text("rem Generated by git-autorun")
        self.assertEqual(a.write_launcher(self.d, "npm start", self.log).name, "start.bat")


if __name__ == "__main__":
    unittest.main(verbosity=2)
